language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
before_deploy: npm run build
deploy:
  provider: npm
  email: sdk@qiniu.com
  skip_cleanup: true
  api_key:
    secure: L9V1k9Y6CFC5fIBRbGbpvhpb004kI9Z/Wvwp5xGnVuGO3n6OfEVoaX7gSLpOkyx4kZfzEEh+R9xriJAeXBfLjiigP1FrKm+EQ92VlkjGh+Dlc4NDwEO00RczfUxI4bQG/HVaVTsQs+EqCnkfsp403wECwuBS68zYtsJZldREmDo=
  on:
    tags: true
    repo: qiniu/js-sdk
